
/******************************************************************************
 *
 * FILE NAME: ultraSonic
 *
 * AUTHOR: Ahmed Gamal Helmy
 *
 * DESCRIPTION: source file for ultraSonic
 *
 *******************************************************************************/
#include "ultraSonic.h"

/***************************************************************************
 *                           global variables
 ***************************************************************************/
static uint8 g_edgeCount = 0;
static uint16 g_timeHigh = 0;




/*
 * Description :
 * Initialize the Ultrasonic:
 * 1. Setup the UltraSonic pins directions by use the GPIO driver.
 * 2. Setup the ICU call back function
 */

void Ultrasonic_init(void){

	/*****************************************************************************
	 *                                ICU_CONFIG
	 *****************************************************************************/

	Icu_ConfigType Icu_Config = {ULTRASONIC_ICU_CLOCK,ULTRASONIC_FIRST_EDGE};
	/*****************************  INIT FUNCTION ****************************/
	Icu_init(&Icu_Config);

	/************************set call back *************************/
	Icu_setCallBack(Ultrasonic_edgeProcessing) ;
	/****************set direction of trigger & echo  ********************/
	//GPIO_setupPinDirection(ULTRASONIC_ECHO_PORT_ID, ULTRASONIC_ECHO_PIN_ID, PIN_INPUT);
	GPIO_setupPinDirection(ULTRASONIC_TRIGGER_PORT_ID, ULTRASONIC_TRIGGER_PIN_ID, PIN_OUTPUT);
	GPIO_writePin(ULTRASONIC_TRIGGER_PORT_ID, ULTRASONIC_TRIGGER_PIN_ID, LOGIC_LOW);
}

/*
 * Description :
 * Send the Trigger pulse to the ultrasonic.
 */
void Ultrasonic_Trigger(void){

	GPIO_writePin(ULTRASONIC_TRIGGER_PORT_ID, ULTRASONIC_TRIGGER_PIN_ID, LOGIC_HIGH);
	_delay_us(10);
	GPIO_writePin(ULTRASONIC_TRIGGER_PORT_ID, ULTRASONIC_TRIGGER_PIN_ID, LOGIC_LOW);

}


/*
 * Description :
 * 1. Send the trigger pulse by using Ultrasonic_Trigger function
 * 2. Start the measurements by the ICU from this moment
 */

uint16 Ultrasonic_readDistance(void){
	uint16 distance=0;
	Ultrasonic_Trigger();

	distance =(float32)g_timeHigh/DIV_FACTOR ;
	return distance ;

}

/*
 * Description :
 * This is the call back function called by the ICU driver
 * This is used to calculate the high time (pulse time) generated by
 * the ultrasonic sensor.
 */


void Ultrasonic_edgeProcessing(void){

	g_edgeCount++;
	if(g_edgeCount == 1)
	{
		/*
		 * Clear the timer counter register to start measurements from the
		 * first detected rising edge
		 */
		Icu_clearTimerValue();
		/* Detect falling edge */
		Icu_setEdgeDetectionType(FALLING);
	}
	else if(g_edgeCount == 2)
	{
		/* Store the High time value */
		g_timeHigh = Icu_getInputCaptureValue();
		/* Clear the timer counter register to start measurements again */
		Icu_clearTimerValue();
		/* Detect rising edge */
		Icu_setEdgeDetectionType(RISING);
		g_edgeCount=0;
	}

}
