/******************************************************************************
 *
 * FILE NAME: ultraSonic
 *
 * AUTHOR: Ahmed Gamal Helmy
 *
 * DESCRIPTION: header file for ultraSonic
 *
 *******************************************************************************/

#ifndef ULTRASONIC_H_
#define ULTRASONIC_H_
#include "std_types.h"
#include "gpio.h"
#include "icu.h"
#include <util/delay.h>


/*******************************************************************************
 *                                Definitions                                  *
 *******************************************************************************/

#define ULTRASONIC_ECHO_PORT_ID           PORTD_ID
#define ULTRASONIC_ECHO_PIN_ID            PIN6_ID

#define ULTRASONIC_TRIGGER_PORT_ID        PORTB_ID
#define ULTRASONIC_TRIGGER_PIN_ID         PIN5_ID


#define ULTRASONIC_ICU_CLOCK              F_CPU_8
#define ULTRASONIC_FIRST_EDGE             RISING


#define DIV_FACTOR                        57.8

/*******************************************************************************
 *                      Functions Prototypes                                   *
 *******************************************************************************/



/*
 * Description :
 * Initialize the Ultrasonic:
 * 1. Setup the UltraSonic pins directions by use the GPIO driver.
 * 2. Setup the ICU call back function
 */

void Ultrasonic_init(void);

/*
 * Description :
 * Send the Trigger pulse to the ultrasonic.
 */
void Ultrasonic_Trigger(void);


/*
 * Description :
 * 1. Send the trigger pulse by using Ultrasonic_Trigger function
 * 2. Start the measurements by the ICU from this moment
 */

uint16 Ultrasonic_readDistance(void);

/*
 * Description :
 * This is the call back function called by the ICU driver
 * This is used to calculate the high time (pulse time) generated by
 * the ultrasonic sensor.
 */


void Ultrasonic_edgeProcessing(void);

#endif /* ULTRASONIC_H_ */
